site_name: Cextra Wiki
theme:
  name: material # A clean, modern documentation theme
plugins:
  - search     # Enables a built-in search bar
docs_dir: .    # Tells MkDocs to look at the root folder for your markdown files
